# Generated by Django 5.0.6 on 2025-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
